server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: ingress-service

  threads:
    virtual:
      enabled: true
      
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: ingress-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.orderlifecycle.ingress_service.*"
        spring.json.add.type.headers: "false"

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:my-default-secret-key-only-for-local-dev-1234567890}
    expiration-time-ms: ${JWT_EXPIRATION_TIME_MS:7200000}

